### ISSUE TITLE
chars \ " make parse issue

### ISSUE THREAD

**Issue by kwladyka** [zlabjp/kubernetes-resource#13]
`kubectl: patch deployment bugsystem -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"updated_at\":\"`date +'%s'`\"}}}}}"`

```
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
+ kubectl patch deployment bugsystem -p '"{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"updated_at\":\"`date' '+'\''%s'\''`\"}}}}}"'
error: unable to parse "\"{\\\"spec\\\":{\\\"template\\\":{\\\"metadata\\\":{\\\"labels\\\":{\\\"updated_at\\\":\\\"`date": yaml: found unexpected end of stream
```

Look at `'`. This char wrap `"{...}"` for some reason and probably this make an issue.

Not really sure it is bug on concourse level or resource level and how to fix it.

**Comment by superbrothers** [comment]
Thank you. I'll check it out.

**Comment by superbrothers** [comment]
#14 fixed this issue, and we released new version. Please check it.
