### ISSUE TITLE
configuration with Google Container Engine

### ISSUE THREAD

**Issue by rjain-pivotal** [zlabjp/kubernetes-resource#17]
How to configure this resource with the google container engine and the service account key?

**Comment by marceldegraaf** [comment]
I would love to know this too.

**Comment by superbrothers** [comment]
We recommends using a serviceaccount. First you should create a serviceaccount, and create a rolebinding for the serviceaccount which is bound an appropriate role.

```
$ kubectl create serviceaccount bot
serviceaccount "bot" created
$ kubectl create rolebinding bot --clusterrole=edit --serviceaccount=default:bot
rolebinding "bot" created
```

Next you should build a kubeconfig from the serviceaccount. `create-kubeconfig` is a handy script which builds a kubeconfig from a serviceaccount. See https://github.com/zlabjp/kubernetes-scripts.

```
$ create-kubeconfig bot
```

If you don't prefer to use a kubeconfig, you can also use cluster configs.

```bash
## server
kubectl config view --minify -o json | jq -r '.clusters[0].cluster.server'
## token
kubectl get secret bot-token-mslxf -o json | jq -r '.data.token' | base64 -d
## namespace
kubectl get secret bot-token-mslxf -o json | jq -r '.data.namespace' | base64 -d
## certificate_authority
kubectl get secret bot-token-mslxf -o json | jq -r '.data["ca.crt"]' | base64 -d
```

Please see the below as reference. Thanks.

- https://github.com/zlabjp/concourse-meetup-tokyo-7-demo/blob/master/ci/pipeline.yml
- https://github.com/zlabjp/kubernetes-resource#example

**Comment by superbrothers** [comment]
@rjain-pivotal @marceldegraaf Has this issue been resolved? Please reopen this issue if it has not been resolved.
