### ISSUE TITLE
Configure container environment

### ISSUE THREAD

**Issue by maxfrigge** [zlabjp/kubernetes-resource#28]
Is there a way to configure the container environment? I would like to pass secrets (e.g. database uri) to the container.

**Comment by superbrothers** [comment]
You can use Kubernetes Secrets resource.

- [Secrets \- Kubernetes](https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-manually)
- [Distribute Credentials Securely Using Secrets \- Kubernetes](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/)

**Comment by maxfrigge** [comment]
I was hoping to pass along my vault secrets from pipeline to the containers. Thinking about it though, it's probably best to have as few secrets as possible available in the pipeline tasks and use other means to provide them at runtime.

Thanks!

**Comment by superbrothers** [comment]
To use concourse-vault-resource and kubernetes-resource togetter might be achieved your hope.

1. Create a new secret object when your vault secrets are updated
    - `kubectl create secret my-secret-$(date +%s) --from-file=password-file`
1. Replace the secret name object name used in manifest files with the new secret object name using something, for example
1. Apply replaced manifest files using `kubectl apply`

It is better that existing secret/configmap objects are immutable for safe rollback.

- https://github.com/Docurated/concourse-vault-resource

**Comment by maxfrigge** [comment]
Thanks for the hint! I Was't aware of this resource yet.
