### ISSUE TITLE
Not able to connect to kubernetes cluster

### ISSUE THREAD

**Issue by sanjay2916** [zlabjp/kubernetes-resource#31]
+ kubectl config set-credentials auth --token=**********
User "auth" set.
+ kubectl config set-cluster cluster --server=https:/com --certificate-authority=/kubernetes-resource-ca_file.3Wd9PD
Cluster "cluster" set.
+ kubectl config set-context kubernetes-resource --user=auth --cluster=cluster --namespace=default
Context "kubernetes-resource" created.
+ kubectl config use-context kubernetes-resource
Switched to context "kubernetes-resource".
+ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:14:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: x509: certificate signed by unknown authority
ERROR: Failed with error code 1

**Comment by crows9p** [comment]
Me, too.

+ kubectl config set-credentials auth --token=**********
User "auth" set.
+ kubectl config set-cluster cluster --server=https://xxxx --certificate-authority=/kubernetes-resource-ca_file.bXBTKV
Cluster "cluster" set.
+ kubectl config set-context kubernetes-resource --user=auth --cluster=cluster --namespace=default
Context "kubernetes-resource" created.
+ kubectl config use-context kubernetes-resource
Switched to context "kubernetes-resource".
+ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: x509: certificate signed by unknown authority

**Comment by crows9p** [comment]
Me, too....

+ kubectl config set-credentials auth --token=**********
User "auth" set.
+ kubectl config set-cluster cluster --server=https://myakscluster-6d88874e.hcp.japaneast.azmk8s.io:443 --certificate-authority=/kubernetes-resource-ca_file.YKVoRJ
Cluster "cluster" set.
+ kubectl config set-context kubernetes-resource --user=auth --cluster=cluster --namespace=default
Context "kubernetes-resource" created.
+ kubectl config use-context kubernetes-resource
Switched to context "kubernetes-resource".
+ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: x509: certificate signed by unknown authority

ERROR: Failed with error code 1

**Comment by sanjay2916** [comment]
I am using working certificate(copied from master node)  and i have used
kubeconfig path but it is also giving error

+ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9",
GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean",
BuildDate:"2018-06-29T01:14:35Z", GoVersion:"go1.9.3", Compiler:"gc",
Platform:"linux/amd64"}
error: Error loading config file "/kubernetes-resource-kubeconfig.wIhcTD":
couldn't get version/kind; json parse error: json: cannot unmarshal string
into Go value of type struct { APIVersion string
"json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }

ERROR: Failed with error code 1



*pipeline.yml:*


resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.9"

resources:
  - name: git-demo
    type: git
    source:
      uri: https://github.com
      branch: master
      username:
      password:
  - name: k8s
    type: kubernetes
    source:
      server: https:/.elb.amazonaws.com
      namespace: default
      token:
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InByb21ldGhldXMtdG9rZW4tczgydGsiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoicHJvbWV0aGV1cyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjcyN2U0NTE1LTgwMzctMTFlOC04NWFmLTAyMWZjNGY3OTA1NCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OnByb21ldGhldXMifQ.KUh2V8V4ZpAWgTboWcLdTNFj8NWxf3z7WpTdxOI1Y9-izRks-xN23hgAWp6MOrapaPyiYmCurJ1XNzvm_TRVM5Z2D1_QFCGRHneEGKlJaxAk-2djbqLBYr4fiQY98NPPM7u73dEKsKiBGHEykgiKpQwlAitX8x8U3z9e6Z57OM_NgBvcBMMjD-tx1JWRsGWh2SBKatD7uljn0BACmmYHDFE96mciRtgcMV6j1CsHGPlemu5-REWMtYyA1gypUcWpfXdr27MzWzPGwuFp24H3EKmbNXVFpg_Y7EvzqcGEHA
      certificate_authority:
LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSBZ0lNRlQ1aHhIdCtQcDNmSHlpeE1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1UZ3dOekF6TURVeU5qVTVXaGNOTWpnd056QXlNRFV5TmpVNQpXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXFUMU5JRE9NYUtBSlhzM0ZvY01Majh4QW9pMmtyU1htS2dGYkF0V3hycU5VWHUyc0VXRGsKWmdkUzJlN2wzUFJCenNSWFl3RVRTZExyQ2lQTTJ2cGZHVg0TVNkanVlcmt5VHI2YUpjS0lwM1cxTWgzM0lNWk5OMnkvQ21TSXhtQ3p5Y2tRbHlmWnAxOTNZS2VECldzZFpmcOcWRoRVdwUkNlSi9nU1hlVXVwRi9zWUQvY2ZkaStkMgpaZGgwS2ZvaE9MVXVWT0gxN1BaTG9SOXdseHRuVWFGSVF3SURBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFiZ2NIZlRqNGYrWW0KVXQ0VmgvU0Q0VlhBRDRscWJDSENjak1USzZjRTU3SkoxZ3JNUlVKTlVyZzBaUk1lVzllVlViMW5sTEs1TlNKMgowNExPb0lpUmNRaDRpaDFIVzFnUFIrQ3FiZDU3Mmc4L0V4ZWVmL1piWC95TTYrV2crUVA1T1pPcXBRM2RxRlpWCjlwbExxb2pGZDJ4OXdOWGhZbEI3QTFOZnZpTkFTVTNhcGlsZkdQSXhzV1VoSUExZGlnYmVWYWRFOWI0VDlsQVQKTGtsVnNJRE9hSkRsODROTVVoSHFxTjEwSm5VdytsNDYyRG91S0o4bGdDZVY4MTRENE5CMXN2TVJiRVlwbUVrOApXUHZaVk04VG1UZ20xb29IWWs4L3hDOFVmUDI0QStrL2h0S084ZzRiVDNLZlFxOGNWYjV3OFRMVWdwc0JQYURvCkpTNmowdXUyOFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
