### ISSUE TITLE
Wait for pods to be ready status returns none for pods with Pending status

### ISSUE THREAD

**Issue by Joz73** [zlabjp/kubernetes-resource#34]
**_Version:_**
repository: zlabjp/kubernetes-resource
tag: "1.10"

Using above concourse resource "Waiting for pods to be ready" status check using following template returns nothing for pod with status pending.

template="$(cat <<EOL
{{- range .items -}}
{{- if and (not .metadata.deletionTimestamp) (ne .status.phase "Failed") (ne .status.phase "Succeeded") -}}
{{.metadata.name}}{{range .status.conditions}}{{if eq .type "Ready"}} {{.status}}{{end}}{{end}}{{"\\n"}}
{{- end -}}
{{- end -}}
EOL
)"

**Below is output from running with this template in my k8s environment:**

[root@k8s-master1 system-assets-service]# kubectl get pods -n ngci -o wide --show-labels
NAME                                    READY     STATUS    RESTARTS   AGE       IP        NODE      LABELS
system-assets-service-55f7856f5-sfw22   0/3       Pending   0          12m       <none>    <none>    app=system-assets-service,pod-template-hash=119341291,version=0.0.1-dev.4

[root@k8s-master1 system-assets-service]# echo $template
{{- range .items -}} {{- if and (not .metadata.deletionTimestamp) (ne .status.phase "Failed") (ne .status.phase "Succeeded") -}} {{.metadata.name}}{{range .status.conditions}}{{if eq .type "Ready"}} {{.status}}{{end}}{{end}}{{"\n"}} {{- end -}} {{- end -}}

[root@k8s-master1 system-assets-service]# kubectl get pods -o template --template="$template" -n ngci
system-assets-service-55f7856f5-sfw22
 
**Job definition in Concourse:**
- name: job-k8s-deployment
  public: true
  serial: true
  plan:
  - get: service-repo
    passed: [job-build-((service-name))]
    trigger: true
  - put: k8s
    params:
      kubectl: apply -f service-repo/deployment.yml
      namespace: ngci
      wait_until_ready: 60
      wait_until_ready_interval: 5
      wait_until_ready_selector: app=((service-name))
  - put: k8s
    params:
      kubectl: get pods -o wide --show-labels
      namespace: ngci
      wait_until_ready: 60
      wait_until_ready_interval: 5
      wait_until_ready_selector: app=((service-name))
    on_failure:
      put: k8s
      params:
        namespace: ngci
        kubectl: delete -f service-repo/deployment.yml

**Return Status Concourse:**
+ kubectl get pods -o wide --show-labels
NAME                                    READY     STATUS    RESTARTS   AGE       IP              NODE                        LABELS
system-assets-service-55f7856f5-k979t   0/3       Pending   0          1m        <none>          <none>                      app=system-assets-service,pod-template-hash=119341291,version=0.0.1-dev.4
Waiting for pods to be ready for 60s (interval: 5s, selector: app=system-assets-service)
Waiting for pods to be ready... (0/0)

**Request:**
Return value for pods with pending status so concourse does not continue when pods are in pending status.

**Comment by superbrothers** [comment]
Thank you for reporting. I think this resource should be changed to your request's behavior.

> Request:
> Return value for pods with pending status so concourse does not continue when pods are in pending status.

@yuanying  WDYT?

**Comment by yuanying** [comment]
This should be fixed. I'll check.

**Comment by Joz73** [comment]
Thanks guys!
