### ISSUE TITLE
How to run docker container?

### ISSUE THREAD

**Issue by christopherwoo** [zlabjp/kubernetes-resource#36]
In docker container: 
> #kubectl get pod

It returns:
> The connection to the server localhost:8080 was refused - did you specify the right host or port?

How to handle this?

**Comment by superbrothers** [comment]
Did you run `fly hijack`, then faced this situation? I don't understand your situation.

**Comment by superbrothers** [comment]
@christopherwoo This issue is inactivity, so I'll close it. If you have any issues, please feel free to reopen this issue. Thanks.
