### ISSUE TITLE
You must specify "server" and "token"

### ISSUE THREAD

**Issue by max-rocket-internet** [zlabjp/kubernetes-resource#42]
Hey I'm testing concourse on k8s, installed from the stable chart.

I have set `rbac.workerServiceAccountName` to a service account that has access to modify deployments on this cluster.

I get this error:

```
ERROR: You must specify "server" and "token", if not specify "kubeconfig".
```

Do I really need to specify these when the whole thing is already running on k8s? i.e. the token and endpoint to access the k8s API should all be available. Or I still need to set these?

**Comment by superbrothers** [comment]
kubernetes-resource don't support using serviceaccount token in a container. Therefore you need to set token and server source params.

**Comment by max-rocket-internet** [comment]
OK
