### ISSUE TITLE
Support token when passing in kubeconfig

### ISSUE THREAD

**Issue by wernerb** [zlabjp/kubernetes-resource#45]
Our situation is that we give out kubeconfigs **without** secrets so that users can put them in their git repositories. We then provision the token as a separate secret to be fetched with vault or something else.

The current common.sh however, does not allow the token to be passed in if you pass in a `kubeconfig` or `kubeconfig_file`. 

I have made a PR to fix this which is backwards compatible and just moves the existing logic.

We really love this resource and especially the wait until ready logic and hope the PR could be added or in some other form our case be supported. Thanks!

**Comment by wernerb** [comment]
@superbrothers I see that there's a new pull request with this code in it. Did something go wrong? Any way I can help?

**Comment by superbrothers** [comment]
@wernerb Could you try to use `zlabjp/kubernetes-resource:edge` in your pipeline? It is the edge version built from the master branch.
