### ISSUE TITLE
Error loading config file: did not find expected key

### ISSUE THREAD

**Issue by lmdehaas** [zlabjp/kubernetes-resource#47]
We've been using this resource for a while without any issues, until we suddenly seem to hit a bug today. We're using an image with tag `1.11`, which to our surprise seems to be updated 13 hours ago. 

Since then, we have this issue:
```
kubectl config set-credentials auth --token=**********
error: Error loading config file "/kubernetes-resource-kubeconfig.9YMQIe": yaml: line 15: did not find expected key
```

The error seems to come from this line (which was recently changed):
https://github.com/zlabjp/kubernetes-resource/blob/master/assets/common.sh#L108

Any idea what may have happened and how we can fix this?

**Comment by superbrothers** [comment]
Thank you for your report. I will make a patch release quickly.

**Comment by superbrothers** [comment]
I've made the patch release v1.4.1, and `zlabjp/kubernetes-resource:1.11` has been updated.

**Comment by superbrothers** [comment]
@lmdehaas Could you show me the full log when the job faild? If possible, in addition to the log, please show me the source configuration of kubernetes-resource without a token?

**Comment by superbrothers** [comment]
@lmdehaas Could you show me the full log when the job faild? If possible, in addition to the log, please show me the source configuration of kubernetes-resource without a token?
