### ISSUE TITLE
Possibilty to get a resource from kubernetes

### ISSUE THREAD

**Issue by stijndehaes** [zlabjp/kubernetes-resource#62]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- feature

Would you be open to a PR expanding the in to do a kubectl get command to get something out of kubernetes. We would like some info residing in kubernetes to continue our build. For now we will not use it as a trigger.

**Comment by superbrothers** [comment]
What is your use-cases of the in to do a kubectl get command? If you want to do that, in my opinion, you should develop your own custom controller.
